export const UPDATE_RANDOM_BANNER_PRODUCTS = 'UPDATE_RANDOM_BANNER_PRODUCTS';
export const SET_ERROR = 'SET_ERROR';
export const FETCH_BANNER = 'FETCH_BANNER';

export default {
  UPDATE_RANDOM_BANNER_PRODUCTS,
  SET_ERROR,
  FETCH_BANNER,
};
