export const MODAL_ROOT = 'modal-root';
export const SHOW_OVERLAY_MODAL = 'SHOW_OVERLAY_MODAL';
export const HIDE_OVERLAY_MODAL = 'HIDE_OVERLAY_MODAL';
export const SET_OVERLAY_MESSAGE = 'SET_OVERLAY_MESSAGE';
export const SET_AND_SHOW_OVERLAY_MESSAGE = 'SET_AND_SHOW_OVERLAY_MESSAGE';
